### ISSUE TITLE
getHost().getProperty doesn't  correctly work  

### ISSUE THREAD

**Issue by kenenbek** [mquinson/simgrid#74] opened 2016-04-11 21:23 UTC
I insert two line of code with setProperty in java examples of masterSlave simulation (Slave.java).
```
			try {
				getHost().setProperty("busy", "yes");
				task.execute();
				getHost().setProperty("busy", "no");
			} catch (TaskCancelledException e) {

			}
```
Then I call getHost().getProperty("busy"), which gives me "busy".
[Screenshot](https://pp.vk.me/c626517/v626517287/3992/WsxwTRtFeD0.jpg)
blue line on screenshot is current line of code.

**Comment by mquinson** [comment] 2016-04-11 21:25
Hello kenenbek
this is not a MWE in the sense that I cannot save this in a file, compile it and run it. You need to add the missing content so that it becomes a self-contained program that I can easily use to debug the problem.
You need to help me helping you ;)

**Comment by kenenbek** [comment] 2016-04-11 21:27
The whole code are from [here](https://github.com/mquinson/simgrid/tree/master/examples/java/app/masterworker). I just added two lines with setProperty().

**Comment by frs69wq** [comment] 2016-04-12 08:24
There was a bug in the bindings, fixed in 8b8fd9b26d58068fdc1867ba8e84781992a51c0d 2 months ago. It is now tested and works in3.13 (see https://github.com/mquinson/simgrid/blob/master/examples/java/io/storage/Client.java#L52)

**Comment by randomstuff** [comment] 2016-04-12 15:01
I guess we should cherry-pick this change for 3.12.

**Comment by mquinson** [comment] 2016-04-12 17:02
Or we should release 3.13.

**Comment by kenenbek** [comment] 2016-04-12 20:11
Sorry. I had to run simgrid_update_xml.pl with arguments: platform.xml and deployment.xml. Now it is working.

**Comment by mquinson** [comment] 2016-04-12 20:42
I'm closing the issue as this is fixed in the git.

**Closed by mquinson** 2016-04-12 20:42 UTC

**Comment by kenenbek** [comment] 2016-04-12 23:59
I know, maybe, it's stupid request. If it is possible, could you implement getProperty() in 3.12 version. Because 3.13 version after some running  "hangs". It is not real hanging, application is running, but it doesn't give any errors or messages. 
[Screenshot](https://pp.vk.me/c626517/v626517287/3d59/Uc3ls4NHdTM.jpg)

**Comment by mquinson** [comment] 2016-04-13 16:30
Nope, we won't do that. Try increasing the level of logging to see what's happening. If there is a bug, we'll fix it. But we won't add feature to the already released version, it cannot be ;)

**Comment by kenenbek** [comment] 2016-04-13 16:40
Okay, I understand you. I will look for an error. But formally getProperty,
setProperty and getLoad are not new features.

2016-04-13 19:30 GMT+03:00 Martin Quinson <notifications@github.com>:

**Comment by frs69wq** [comment] 2016-04-13 16:55
setProperty and getProperty are now tested functions in 3.13.
They were buggy but untested in 3.12. The thing is that our tests do not hang. So it might come from your usage of it, usage that we can't reproduce by lack of a MWE that you still fail to provide.

Reopening close issues to complain while you don't provide what could help us to help you is not a civil way to proceed. And no, a snapshot is not a MWE.

**Comment by frs69wq** [comment] 2016-04-13 17:06
To be more explicit, the past issues tended to blame simgrid when your usage of it was to blame: exceptions are thrown when they should, unimplemented features are properly advertised, ... However you call those errors from simgrid. Here again, it's "it hangs, find me a solution"

We repetitively asked for minimal working example because it forces you to isolate the potential bug from the rest of your code. Then you can blame simgrid. Right now, each time something happens, you blame simgrid, even when what's happening is legit. 

I don't know if you know that story about the boy who called wolf ...

**Comment by kenenbek** [comment] 2016-04-13 17:10
​Yes, you are right. Sorry for causing inconvenience.​

2016-04-13 20:06 GMT+03:00 Frederic Suter <notifications@github.com>:

> To be more explicit, the past issues tended to blame simgrid when your
> usage of it was to blame: exceptions are thrown when they should,
> unimplemented features are properly advertised, ... However you call those
> errors from simgrid. Here again, it's "it hangs, find me a solution"
>
> We repetitively asked for minimal working example because it forces you to
> isolate the potential bug from the rest of your code. Then you can blame
> simgrid. Right now, each time something happens, you blame simgrid, even
> when what's happening is legit.
>
> I don't know if you know that story about the boy who called wolf ...
>
>
>
