### ISSUE TITLE
Missing PMPI_Comm_set_errhandler in smpi

### ISSUE THREAD

**Issue by rchic** [mquinson/simgrid#29] opened 2015-09-29 09:48 UTC
Hi all,

With Arnaud Giersch we tried to compile Petsc with smpi.
After some difficulties we succeed to compile it. When we run an example of petsc, it fails with the message : MPI_Comm_set_errhandler Not yet implemented
Is it possible to implement it?
Maybe other mpi functions will be needed after...

Thanks in advance,

Raphaël Couturier

**Comment by adegomme** [comment] 2015-10-24 20:36
Hi,

Sorry for the delay. SMPI should only print a warning when it encounters an unimplemented function (and as this one is not really important, it should be enough). It looks like you are using an older version (<3.11), or am I mistaken ? The 3.12 version has been released recently, you should upgrade to this one if possible, or use the github version. 

Regards
Augustin Degomme

**Comment by rchic** [comment] 2016-01-08 10:45
Hi,

With Arnaud Giersch, we solved our problem. With simgrid 3.12, we could recompile the Petsc library in static and with --cfg=smpi/privatize_global_variables:yes, now simgrid is able to simulate a Petsc code using several mpi process. We don't know what was the problem (maybe the old simgrid version or maybe the use of private variables). Nevertheless we will try to use simgrid to simulate big applications with Petsc.
There is still this message (which is only a warning)
[smpi_pmpi/WARNING] Not yet implemented : PMPI_Comm_set_errhandler. Please contact the Simgrid team if support is needed

Thanks

Raphaël

**Comment by adegomme** [comment] 2016-01-08 14:11
Hi,
Glad to see that the problem is gone. The warning is quite explicit, this feature is only useful in case of error during execution, to tell the MPI library how to react. Usually in case of error on one node, the execution stops on all others. This is the case in SMPI as well. But MPI allows to handle errors manually and more precisely, or even to trigger its own errors. We don't plan on implementing these features for now, except if this is absolutely necessary to someone's experiments. 

The comm_set_errhandler call is usually done at the creation of a communicator, which should not be done too often, so the output should not be too polluted by these messages. It can be silenced by the command line flag --log=smpi_pmpi.thresh:critical . But be advised this could maybe hide some other messages in the process.

Regards,
Augustin

**Comment by mquinson** [comment] 2016-01-08 20:04
I'm happy to see that the problem is fixed. I'm thus closing the bug.

Have a nice and enjoyable experiment ;)

**Closed by mquinson** 2016-01-08 20:04 UTC
