### ISSUE TITLE
The SimGrid storage issues

### ISSUE THREAD

**Issue by cchb1990** [mquinson/simgrid#36] opened 2015-11-28 13:10 UTC
I found the SimGrid uses a file,such as context.txt,to simulate the content on the disk. But after I did some operations like msg_file_move or msg_file_write on the disk, I found context.txt was not changed. I thought since I created a new file, such as hello.txt,of size 100, then context.txt should have one more line 'hello.txt 100'.

**Comment by mquinson** [comment] 2015-12-18 00:23
I think that the context.txt is only the intial value of the content. It is not intended to be changed during the simulation: it's somehow part of the platform file.
@frs69wq could you confirm?

**Comment by frs69wq** [comment] 2015-12-18 08:19
I do confirm that this text file given as input in the XML just describes the initial contents of a storage elements. Each of its line is loaded as a dictionary entry at parsing time. Then this file is never accessed anymore.

**Comment by mquinson** [comment] 2015-12-18 16:08
I am thus closing the issue: this is not a bug, but the expected behavior. 

Thanks for reporting, Mt.

**Closed by mquinson** 2015-12-18 16:08 UTC
